logging:
  level:
    root: INFO
  file:
    name: ${user.dir}/logs/java.log
server:
  port: 80

crudImplementation: Hibernate

jdbc:
    url: jdbc:mysql://localhost:3306
    username: root
    password: roottest
    driver: com.mysql.cj.jdbc.Driver
    dbname: card_db
    initScript: src/main/resources/DBTransportCard.sql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card_db?createDatabaseIfNotExist=true
    username: root
    password: roottest
  jpa:
    show-sql: true
    open-in-view: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  liquibase:
#    user: root
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
#    contexts: dev
