logging:
  level:
    root: INFO
  file:
    name: ${user.dir}/logs/java.log
server:
  port: 80
hello: Spring
dbAdapter:

spring:
  datasource:
    url: jdbc:mysql://localhost:80/carddb
    username: root
    password: roottest
    driver-class-name: com.mysql.cj.jdbs.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
