logging:
  level:
    root: INFO
  file:
    name: ${user.dir}/logs/java.log
server:
  port: 80

crudImplementation: Hibernate

jdbc:
#    url: jdbc:postgresql://localhost:5432
    url: jdbc:mysql://localhost:3306
#    username: postgres
    username: root
    password: roottest
#    driver: org.postgresql.Driver
    driver: com.mysql.cj.jdbc.Driver
    dbname: card_db
    initScript: src/main/resources/DBTransportCard.sql

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/card_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/card_db?createDatabaseIfNotExist=true
#    username: postgres
    username: root
    password: roottest
  jpa:
    show-sql: true
    open-in-view: false
#    database: postgresql
    database: mysql
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
